// Generated by @wagmi/cli@0.1.15 on 5/4/2023 at 6:35:28 PM
import {
  useContract,
  UseContractConfig,
  useContractRead,
  UseContractReadConfig,
} from 'wagmi'
import { ReadContractResult } from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PerpsV2MarketData
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export const perpsV2MarketDataABI = [
  {
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {
        name: '_resolverProxy',
        internalType: 'contract IAddressResolver',
        type: 'address',
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'allMarketSummaries',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.MarketSummary[]',
        type: 'tuple[]',
        components: [
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'asset', internalType: 'bytes32', type: 'bytes32' },
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
          { name: 'price', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSize', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSkew', internalType: 'int256', type: 'int256' },
          { name: 'marketDebt', internalType: 'uint256', type: 'uint256' },
          {
            name: 'currentFundingRate',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'currentFundingVelocity',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'feeRates',
            internalType: 'struct PerpsV2MarketData.FeeRates',
            type: 'tuple',
            components: [
              { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
              { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
              {
                name: 'takerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'takerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'allProxiedMarketSummaries',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.MarketSummary[]',
        type: 'tuple[]',
        components: [
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'asset', internalType: 'bytes32', type: 'bytes32' },
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
          { name: 'price', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSize', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSkew', internalType: 'int256', type: 'int256' },
          { name: 'marketDebt', internalType: 'uint256', type: 'uint256' },
          {
            name: 'currentFundingRate',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'currentFundingVelocity',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'feeRates',
            internalType: 'struct PerpsV2MarketData.FeeRates',
            type: 'tuple',
            components: [
              { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
              { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
              {
                name: 'takerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'takerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'globals',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.FuturesGlobals',
        type: 'tuple',
        components: [
          {
            name: 'minInitialMargin',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'liquidationFeeRatio',
            internalType: 'uint256',
            type: 'uint256',
          },
          { name: 'minKeeperFee', internalType: 'uint256', type: 'uint256' },
          { name: 'maxKeeperFee', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {
        name: 'market',
        internalType: 'contract IPerpsV2MarketViews',
        type: 'address',
      },
    ],
    name: 'marketDetails',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.MarketData',
        type: 'tuple',
        components: [
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'baseAsset', internalType: 'bytes32', type: 'bytes32' },
          { name: 'marketKey', internalType: 'bytes32', type: 'bytes32' },
          {
            name: 'feeRates',
            internalType: 'struct PerpsV2MarketData.FeeRates',
            type: 'tuple',
            components: [
              { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
              { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
              {
                name: 'takerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'takerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
          {
            name: 'limits',
            internalType: 'struct PerpsV2MarketData.MarketLimits',
            type: 'tuple',
            components: [
              { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
              {
                name: 'maxMarketValue',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
          {
            name: 'fundingParameters',
            internalType: 'struct PerpsV2MarketData.FundingParameters',
            type: 'tuple',
            components: [
              {
                name: 'maxFundingVelocity',
                internalType: 'uint256',
                type: 'uint256',
              },
              { name: 'skewScale', internalType: 'uint256', type: 'uint256' },
            ],
          },
          {
            name: 'marketSizeDetails',
            internalType: 'struct PerpsV2MarketData.MarketSizeDetails',
            type: 'tuple',
            components: [
              { name: 'marketSize', internalType: 'uint256', type: 'uint256' },
              {
                name: 'sides',
                internalType: 'struct PerpsV2MarketData.Sides',
                type: 'tuple',
                components: [
                  { name: 'long', internalType: 'uint256', type: 'uint256' },
                  { name: 'short', internalType: 'uint256', type: 'uint256' },
                ],
              },
              { name: 'marketDebt', internalType: 'uint256', type: 'uint256' },
              { name: 'marketSkew', internalType: 'int256', type: 'int256' },
            ],
          },
          {
            name: 'priceDetails',
            internalType: 'struct PerpsV2MarketData.PriceDetails',
            type: 'tuple',
            components: [
              { name: 'price', internalType: 'uint256', type: 'uint256' },
              { name: 'invalid', internalType: 'bool', type: 'bool' },
            ],
          },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'marketKey', internalType: 'bytes32', type: 'bytes32' }],
    name: 'marketDetailsForKey',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.MarketData',
        type: 'tuple',
        components: [
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'baseAsset', internalType: 'bytes32', type: 'bytes32' },
          { name: 'marketKey', internalType: 'bytes32', type: 'bytes32' },
          {
            name: 'feeRates',
            internalType: 'struct PerpsV2MarketData.FeeRates',
            type: 'tuple',
            components: [
              { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
              { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
              {
                name: 'takerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'takerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
          {
            name: 'limits',
            internalType: 'struct PerpsV2MarketData.MarketLimits',
            type: 'tuple',
            components: [
              { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
              {
                name: 'maxMarketValue',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
          {
            name: 'fundingParameters',
            internalType: 'struct PerpsV2MarketData.FundingParameters',
            type: 'tuple',
            components: [
              {
                name: 'maxFundingVelocity',
                internalType: 'uint256',
                type: 'uint256',
              },
              { name: 'skewScale', internalType: 'uint256', type: 'uint256' },
            ],
          },
          {
            name: 'marketSizeDetails',
            internalType: 'struct PerpsV2MarketData.MarketSizeDetails',
            type: 'tuple',
            components: [
              { name: 'marketSize', internalType: 'uint256', type: 'uint256' },
              {
                name: 'sides',
                internalType: 'struct PerpsV2MarketData.Sides',
                type: 'tuple',
                components: [
                  { name: 'long', internalType: 'uint256', type: 'uint256' },
                  { name: 'short', internalType: 'uint256', type: 'uint256' },
                ],
              },
              { name: 'marketDebt', internalType: 'uint256', type: 'uint256' },
              { name: 'marketSkew', internalType: 'int256', type: 'int256' },
            ],
          },
          {
            name: 'priceDetails',
            internalType: 'struct PerpsV2MarketData.PriceDetails',
            type: 'tuple',
            components: [
              { name: 'price', internalType: 'uint256', type: 'uint256' },
              { name: 'invalid', internalType: 'bool', type: 'bool' },
            ],
          },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'markets', internalType: 'address[]', type: 'address[]' }],
    name: 'marketSummaries',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.MarketSummary[]',
        type: 'tuple[]',
        components: [
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'asset', internalType: 'bytes32', type: 'bytes32' },
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
          { name: 'price', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSize', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSkew', internalType: 'int256', type: 'int256' },
          { name: 'marketDebt', internalType: 'uint256', type: 'uint256' },
          {
            name: 'currentFundingRate',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'currentFundingVelocity',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'feeRates',
            internalType: 'struct PerpsV2MarketData.FeeRates',
            type: 'tuple',
            components: [
              { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
              { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
              {
                name: 'takerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'takerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'marketKeys', internalType: 'bytes32[]', type: 'bytes32[]' },
    ],
    name: 'marketSummariesForKeys',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.MarketSummary[]',
        type: 'tuple[]',
        components: [
          { name: 'market', internalType: 'address', type: 'address' },
          { name: 'asset', internalType: 'bytes32', type: 'bytes32' },
          { name: 'key', internalType: 'bytes32', type: 'bytes32' },
          { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
          { name: 'price', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSize', internalType: 'uint256', type: 'uint256' },
          { name: 'marketSkew', internalType: 'int256', type: 'int256' },
          { name: 'marketDebt', internalType: 'uint256', type: 'uint256' },
          {
            name: 'currentFundingRate',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'currentFundingVelocity',
            internalType: 'int256',
            type: 'int256',
          },
          {
            name: 'feeRates',
            internalType: 'struct PerpsV2MarketData.FeeRates',
            type: 'tuple',
            components: [
              { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
              { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
              {
                name: 'takerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'takerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
              {
                name: 'makerFeeOffchainDelayedOrder',
                internalType: 'uint256',
                type: 'uint256',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'marketKey', internalType: 'bytes32', type: 'bytes32' }],
    name: 'parameters',
    outputs: [
      {
        name: '',
        internalType: 'struct IPerpsV2MarketSettings.Parameters',
        type: 'tuple',
        components: [
          { name: 'takerFee', internalType: 'uint256', type: 'uint256' },
          { name: 'makerFee', internalType: 'uint256', type: 'uint256' },
          {
            name: 'takerFeeDelayedOrder',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'makerFeeDelayedOrder',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'takerFeeOffchainDelayedOrder',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'makerFeeOffchainDelayedOrder',
            internalType: 'uint256',
            type: 'uint256',
          },
          { name: 'maxLeverage', internalType: 'uint256', type: 'uint256' },
          { name: 'maxMarketValue', internalType: 'uint256', type: 'uint256' },
          {
            name: 'maxFundingVelocity',
            internalType: 'uint256',
            type: 'uint256',
          },
          { name: 'skewScale', internalType: 'uint256', type: 'uint256' },
          {
            name: 'nextPriceConfirmWindow',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'delayedOrderConfirmWindow',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'minDelayTimeDelta',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'maxDelayTimeDelta',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'offchainDelayedOrderMinAge',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'offchainDelayedOrderMaxAge',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'offchainMarketKey',
            internalType: 'bytes32',
            type: 'bytes32',
          },
          {
            name: 'offchainPriceDivergence',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'liquidationPremiumMultiplier',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'liquidationBufferRatio',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'maxLiquidationDelta',
            internalType: 'uint256',
            type: 'uint256',
          },
          { name: 'maxPD', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {
        name: 'market',
        internalType: 'contract IPerpsV2MarketViews',
        type: 'address',
      },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'positionDetails',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.PositionData',
        type: 'tuple',
        components: [
          {
            name: 'position',
            internalType: 'struct IPerpsV2MarketBaseTypes.Position',
            type: 'tuple',
            components: [
              { name: 'id', internalType: 'uint64', type: 'uint64' },
              {
                name: 'lastFundingIndex',
                internalType: 'uint64',
                type: 'uint64',
              },
              { name: 'margin', internalType: 'uint128', type: 'uint128' },
              { name: 'lastPrice', internalType: 'uint128', type: 'uint128' },
              { name: 'size', internalType: 'int128', type: 'int128' },
            ],
          },
          { name: 'notionalValue', internalType: 'int256', type: 'int256' },
          { name: 'profitLoss', internalType: 'int256', type: 'int256' },
          { name: 'accruedFunding', internalType: 'int256', type: 'int256' },
          { name: 'remainingMargin', internalType: 'uint256', type: 'uint256' },
          {
            name: 'accessibleMargin',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'liquidationPrice',
            internalType: 'uint256',
            type: 'uint256',
          },
          { name: 'canLiquidatePosition', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'marketKey', internalType: 'bytes32', type: 'bytes32' },
      { name: 'account', internalType: 'address', type: 'address' },
    ],
    name: 'positionDetailsForMarketKey',
    outputs: [
      {
        name: '',
        internalType: 'struct PerpsV2MarketData.PositionData',
        type: 'tuple',
        components: [
          {
            name: 'position',
            internalType: 'struct IPerpsV2MarketBaseTypes.Position',
            type: 'tuple',
            components: [
              { name: 'id', internalType: 'uint64', type: 'uint64' },
              {
                name: 'lastFundingIndex',
                internalType: 'uint64',
                type: 'uint64',
              },
              { name: 'margin', internalType: 'uint128', type: 'uint128' },
              { name: 'lastPrice', internalType: 'uint128', type: 'uint128' },
              { name: 'size', internalType: 'int128', type: 'int128' },
            ],
          },
          { name: 'notionalValue', internalType: 'int256', type: 'int256' },
          { name: 'profitLoss', internalType: 'int256', type: 'int256' },
          { name: 'accruedFunding', internalType: 'int256', type: 'int256' },
          { name: 'remainingMargin', internalType: 'uint256', type: 'uint256' },
          {
            name: 'accessibleMargin',
            internalType: 'uint256',
            type: 'uint256',
          },
          {
            name: 'liquidationPrice',
            internalType: 'uint256',
            type: 'uint256',
          },
          { name: 'canLiquidatePosition', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
  },
  {
    constant: true,
    payable: false,
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'resolverProxy',
    outputs: [
      { name: '', internalType: 'contract IAddressResolver', type: 'address' },
    ],
  },
] as const

/**
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export const perpsV2MarketDataAddress = {
  10: '0x340B5d664834113735730Ad4aFb3760219Ad9112',
} as const

/**
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export const perpsV2MarketDataConfig = {
  address: perpsV2MarketDataAddress,
  abi: perpsV2MarketDataABI,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContract}__ with `abi` set to __{@link perpsV2MarketDataABI}__.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketData(
  config: Omit<UseContractConfig, 'abi' | 'address'> & {
    chainId?: keyof typeof perpsV2MarketDataAddress
  } = {} as any,
) {
  return useContract({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    ...config,
  })
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof perpsV2MarketDataABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      TFunctionName,
      TSelectData
    >,
    'abi' | 'address'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"allMarketSummaries"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataAllMarketSummaries<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'allMarketSummaries'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'allMarketSummaries',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'allMarketSummaries',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'allMarketSummaries',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"allProxiedMarketSummaries"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataAllProxiedMarketSummaries<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'allProxiedMarketSummaries'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'allProxiedMarketSummaries',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'allProxiedMarketSummaries',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'allProxiedMarketSummaries',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"globals"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataGlobals<
  TSelectData = ReadContractResult<typeof perpsV2MarketDataABI, 'globals'>,
>(
  config: Omit<
    UseContractReadConfig<typeof perpsV2MarketDataABI, 'globals', TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'globals',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'globals',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"marketDetails"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataMarketDetails<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'marketDetails'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'marketDetails',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'marketDetails',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'marketDetails',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"marketDetailsForKey"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataMarketDetailsForKey<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'marketDetailsForKey'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'marketDetailsForKey',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'marketDetailsForKey',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'marketDetailsForKey',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"marketSummaries"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataMarketSummaries<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'marketSummaries'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'marketSummaries',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'marketSummaries',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'marketSummaries',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"marketSummariesForKeys"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataMarketSummariesForKeys<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'marketSummariesForKeys'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'marketSummariesForKeys',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'marketSummariesForKeys',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'marketSummariesForKeys',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"parameters"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataParameters<
  TSelectData = ReadContractResult<typeof perpsV2MarketDataABI, 'parameters'>,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'parameters',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'parameters',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'parameters',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"positionDetails"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataPositionDetails<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'positionDetails'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'positionDetails',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'positionDetails',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'positionDetails',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"positionDetailsForMarketKey"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataPositionDetailsForMarketKey<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'positionDetailsForMarketKey'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'positionDetailsForMarketKey',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'positionDetailsForMarketKey',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'positionDetailsForMarketKey',
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link perpsV2MarketDataABI}__ and `functionName` set to `"resolverProxy"`.
 *
 * [__View Contract on Optimism Optimism Explorer__](https://explorer.optimism.io/address/0x340B5d664834113735730Ad4aFb3760219Ad9112)
 */
export function usePerpsV2MarketDataResolverProxy<
  TSelectData = ReadContractResult<
    typeof perpsV2MarketDataABI,
    'resolverProxy'
  >,
>(
  config: Omit<
    UseContractReadConfig<
      typeof perpsV2MarketDataABI,
      'resolverProxy',
      TSelectData
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof perpsV2MarketDataAddress } = {} as any,
) {
  return useContractRead({
    abi: perpsV2MarketDataABI,
    address: perpsV2MarketDataAddress[10],
    functionName: 'resolverProxy',
    ...config,
  } as UseContractReadConfig<
    typeof perpsV2MarketDataABI,
    'resolverProxy',
    TSelectData
  >)
}
